### ISSUE TITLE
Bug: Everything is unavailable

### ISSUE THREAD

**Issue by MusicmanP3** [klejejs/ha-thermia-heat-pump-integration#128]
### Issue

After upgrading to 2025.12.0 the integration stopped working. Everything is unavailable.

### Expected Behavior

After upgrading to 2025.12.0 the integration stopped working. Everything is unavailable.

### Debug File Data from "thermia_debug.txt" file

After upgrading to 2025.12.0 the integration stopped working. Everything is unavailable.

### Please check the following before opening a new issue

- [x] I have checked and am running the latest version of the integration
- [x] I have checked and the issue I am reporting is not listed under the [common issues section in README.md](https://github.com/klejejs/ha-thermia-heat-pump-integration?tab=readme-ov-file#common-issues), or the fix listed there does not work

**Comment by MaxVonk** [comment]
Same issue, here's my logs:

Logger: homeassistant.setup
Source: setup.py:343
First occurred: 07:10:46 (1 occurrence)
Last logged: 07:10:46

Setup failed for custom integration 'thermia': Unable to import component: cannot import name 'device_attr' from 'homeassistant.helpers.template' (/usr/src/homeassistant/homeassistant/helpers/template/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1012, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1072, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/thermia/__init__.py", line 16, in <module>
    from .services import ThermiaServicesSetup
  File "/config/custom_components/thermia/services.py", line 10, in <module>
    from homeassistant.helpers.template import device_attr
ImportError: cannot import name 'device_attr' from 'homeassistant.helpers.template' (/usr/src/homeassistant/homeassistant/helpers/template/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1032, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1024, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1072, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1027, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/thermia/__init__.py", line 16, in <module>
    from .services import ThermiaServicesSetup
  File "/config/custom_components/thermia/services.py", line 10, in <module>
    from homeassistant.helpers.template import device_attr
ImportError: cannot import name 'device_attr' from 'homeassistant.helpers.template' (/usr/src/homeassistant/homeassistant/helpers/template/__init__.py)

**Comment by fclauson** [comment]
So that I do no have to update mine and get the error - could someone try the following 

using the file editor edit the service.py in the /homeassistant/custom_components/thermia/services.py

line 10 - change from
from homeassistant.helpers.template import device_attr
to 
from homeassistant.helpers.device_registry import device_attr


you will then need to restart 

lets see if that fixes the issue

**Comment by fclauson** [comment]
Thanks - will pull HA into a VM and play with the update 
probably will be 24hrs before I can get near this

**Comment by klejejs** [comment]
The latest version 5.4.0 fixes the issue. Let me know if there are any more problems.
