### ISSUE TITLE
Credentials are invalid. (Genesis)

### ISSUE THREAD

**Issue by jondavidsson** [klejejs/ha-thermia-heat-pump-integration#69]
I'm getting "Credentials are invalid." with API type set to "genesis". No problem to login at https://online-genesis.thermia.se/

If I try the "classic" the integration is added correctly, but of course no heat pump since that account doesn't have any heat pump installed.

Anyone else having this problem?

**Comment by janner** [comment]
`2024-01-08 10:11:49.213 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Thermia (***username***) for thermia
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/thermia/__init__.py", line 38, in async_setup_entry
    thermia = await hass.async_add_executor_job(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/thermia/__init__.py", line 39, in 
    lambda: Thermia(username, password, api_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ThermiaOnlineAPI/__init__.py", line 17, in __init__
    self.heat_pumps = self.fetch_heat_pumps()
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ThermiaOnlineAPI/__init__.py", line 24, in fetch_heat_pumps
    heat_pumps.append(ThermiaHeatPump(device, self.api_interface))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ThermiaOnlineAPI/model/HeatPump.py", line 89, in __init__
    self.update_data()
  File "/usr/local/lib/python3.11/site-packages/ThermiaOnlineAPI/model/HeatPump.py", line 126, in update_data
    self.__running_operational_statuses = self.__get_running_operational_statuses()
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ThermiaOnlineAPI/model/HeatPump.py", line 485, in __get_running_operational_statuses
    current_operation_mode = [
                             ^
  File "/usr/local/lib/python3.11/site-packages/ThermiaOnlineAPI/model/HeatPump.py", line 486, in 
    value.name
AttributeError: 'dict' object has no attribute 'name'`

**Comment by kstevn** [comment]
Same, since updating to 3.3.0.

**Comment by joakimnord** [comment]
Exactly them same, Calibra 12

**Comment by Er-i-c** [comment]
Same here with Classic

**Comment by zrajna** [comment]
Same here with genesis.

**Comment by Er-i-c** [comment]
And it stopped working again.

**Comment by klejejs** [comment]
Thanks for reporting the issue! Please install the latest `3.3.1` version and report back if there are still issues.

**Comment by jondavidsson** [comment]
Yes, it's working just fine now. Thanks and great work!

**Comment by cmragnar** [comment]
> And it stopped working again.

Same here. 
water_heater entity still says Unknow.

What did work for me in 3.2.0 was Operational status, has now been removed.

**Comment by flexi80** [comment]
Hej, after updating from 3.2 - 3.3.1 I no longer have the operational status showing, it is now marked as unavailable.

**Comment by cmragnar** [comment]
> @cmragnar when you say "water_heater entity still says Unknown", what do mean by that? Could you please post a screenshot of your sensor values and how they look in Thermia Online? Are you familiar with Python? If yes, could you please follow [these instructions](https://github.com/klejejs/python-thermia-online-api#regarding-unsupported-models) and send me the debug file?

Some screnshots.
![Deviceinfo_heatpump](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/52965048/07e6ca5d-20bd-4774-b076-c4c99bab14c9)
![DevTools-water_heater](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/52965048/369420aa-f896-4140-8acc-754d39171d04)

I will look into the Python script.

**Comment by klejejs** [comment]
@flexi80 the operational status sensor was removed as it seemed to be showing incorrect and irrelevant values, and replaced with separate status sensors (different ones shown depending on the heat pump). Did you previously find that operational status showed a valid value for your heat pump and was never "unknown"?
![image](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/24546950/11f51efc-1739-4b65-b271-6b3004ed12ce)

**Comment by klejejs** [comment]
@cmragnar I am sorry, you have quite a different heat pump than mine according to the debug file, so it is hard for me to debug. Could you please elaborate on if you can switch the operation through the UI for your heat pump, which values are switchable and which are not?

**Comment by flexi80** [comment]
@klejejs Hi, yes I've always had the current status of the heat pump working, not the ones you have shown, but the overall status. 

![image](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/121363275/9d667de1-de7e-4c58-8200-f15e8e1c99b2)

**Comment by kstevn** [comment]
I have a Calibra 7 and the operational status has been working fine.
![thermia2](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/150390446/c3662c07-bda9-4783-b19b-5be52fc31b54)
![thermia](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/150390446/69e15266-1e2c-400e-9e5d-0b6327a9924b)

**Comment by cmragnar** [comment]
> @cmragnar I am sorry, you have quite a different heat pump than mine according to the debug file, so it is hard for me to debug. Could you please elaborate on if you can switch the operation through the UI for your heat pump, which values are switchable and which are not?

Not that much.
Temperature, on the status page.
Hotwater (varmvatten)
Hotwater boost.

All this ones is working. Both in 3.2.0 and 3.3.1.

Then smart has been added recently, but that is a completely different story. ;) nothing I use.

![Status](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/52965048/4296213d-f8ae-42a8-96f9-e0e2e955973a)
![Driftinformation_switchable](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/52965048/bf0b3af0-c997-48d6-96d5-583a93ec0a1b)

**Comment by klejejs** [comment]
The Genesis API has been removed by Thermia, thus the API config option has been removed and all heat pumps are now using the classic API. Please install the latest version and check if the issues persist.
For other problems, please create a new issue in GitHub, as it feels like this one talks about different ones.
